# Generated by Django 4.1.2 on 2022-10-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
